
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto : update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true

#cloud:
#  aws:
#    credentials:
#      accessKey:
#      secretKey:
#    s3:
#      bucket:
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#
#jwt:
#  secret:

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 20MB