
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/doAd
    username: sa
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto : create
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 36893483045-coduh0runds4giueq6cpr3s0rnk9vc2e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#cloud:
#  aws:
#    credentials:
#      accessKey:
#      secretKey:
#    s3:
#      bucket:
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#
#jwt:
#  secret:

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 20MB